config/routes.rb
Rails.application.routes.draw do
  resources :standings

  resources :keyvals

  resources :scrape_configs do 
    member do
      get :clone
    end
  end

  resources :images

  resources :widgets

  resources :publish_checkers

  resources :ranks

  root 'ranks#index'

  get 'ranks' => 'ranks#index'

  get 'ranks/week/:week/' => 'ranks#indexWeek'

  get 'statistics' => 'statistics#index'
  get 'about' => 'statistics#about'

end

app/models/standing.rb
class Standing < ActiveRecord::Base

	def self.scrapeData(new_url)
		puts "scraping..."

		#url = "http://mlb.mlb.com/mlb/standings/#20150509"
		url = new_url

		team_xpath = "//*[starts-with(@id, 'standingsTable')]/table/tbody//tr/td[1]/a"
		wins_xpath = "//*[starts-with(@id, 'standingsTable')]/table/tbody//tr/td[2]"
		losses_xpath = "//*[starts-with(@id, 'standingsTable')]/table/tbody//tr/td[3]"
		percentage_xpath = "//*[starts-with(@id, 'standingsTable')]/table/tbody//tr/td[4]"

		# SCRAPING ALGORITHM
		driver = Selenium::WebDriver.for :firefox

		#client = Selenium::WebDriver::Remote::Http::Default.new
		#driver = Selenium::WebDriver.for :phantomjs
		#driver = Selenium::WebDriver.for(:phantomjs, :http_client => client)

	    driver.get "#{url}" # get request for website

	    next_week_sql = "SELECT week FROM standings ORDER BY week DESC LIMIT 1"
	    next_week = Standing.find_by_sql(next_week_sql)
	    if next_week[0].nil?
	    	next_week = 1
	    else
		    next_week = next_week[0].week + 1
		end
	    next_year = 2015

	    teams = driver.find_elements :xpath => "#{team_xpath}"
	    wins = driver.find_elements :xpath => "#{wins_xpath}"
	    losses = driver.find_elements :xpath => "#{losses_xpath}"
	    percentages = driver.find_elements :xpath => "#{percentage_xpath}"

	    # Loop through and print to console every rank and team
	    for i in 0..(teams.size - 1) do
	        team = "#{teams[i].attribute('innerHTML')}"
	        team = NAME_HASHES[team]
	        win = "#{wins[i].attribute('innerHTML')}" # outerHTML of element
	        loss = "#{losses[i].attribute('innerHTML')}" # outerHTML of element
	        percentage = "#{percentages[i].attribute('innerHTML')}" # outerHTML of element


			puts "creating record: #{team} #{win} #{loss} #{percentage}"
			Standing.create(:team => team, :wins => win, :losses => loss, :percentage => percentage,
			 :week => next_week, :year => next_year)
	    end

	# End the Selenium session
	driver.quit()
	end


	#######################################################################################################################

	# Hashing from various names formats to a single standard

	# Hash Format 
	# Key: 		Un-standardized name
	# Value: 	Array of {standardized name, team's image url}

=begin

Standard:
	Colorado Rockies
	Philadelphia Phillies
	Tampa Bay Rays
	Cincinnati Reds
	Texas Rangers
	Houston Astros
	Minnesota Twins
	Arizona Diamondbacks
	Milwaukee Brewers
	Cleveland Indians
	Atlanta Braves
	New York Mets
	San Diego Padres
	New York Yankees
	Chicago Cubs
	Chicago White Sox
	Kansas City Royals
	Miami Marlins
	Oakland Athletics
	Baltimore Orioles
	Boston Red Sox
	Toronto Blue Jays
	Washington Nationals
	Pittsburgh Pirates
	Seattle Mariners
	San Francisco Giants
	St. Louis Cardinals
	Detroit Tigers
	Los Angeles Angels
	Los Angeles Dodgers

=end

	NAME_HASHES = Hash.new

	NAME_HASHES["Washington"] = "Washington Nationals"
	NAME_HASHES["Pittsburgh"] = "Pittsburgh Pirates"
	NAME_HASHES["St. Louis"] = "St. Louis Cardinals"
	NAME_HASHES["Seattle"] = "Seattle Mariners"
	NAME_HASHES["Cleveland"] = "Cleveland Indians"
	NAME_HASHES["LA Dodgers"] = "Los Angeles Dodgers"
	NAME_HASHES["LA Angels"] = "Los Angeles Angels"
	NAME_HASHES["Detroit"] = "Detroit Tigers"
	NAME_HASHES["Baltimore"] = "Baltimore Orioles"
	NAME_HASHES["San Francisco"] = "San Francisco Giants"
	NAME_HASHES["Boston"] = "Boston Red Sox"
	NAME_HASHES["Kansas City"] = "Kansas City Royals"
	NAME_HASHES["Toronto"] = "Toronto Blue Jays"
	NAME_HASHES["Chi Cubs"] = "Chicago Cubs"
	NAME_HASHES["Chi White Sox"] = "Chicago White Sox"
	NAME_HASHES["San Diego"] = "San Diego Padres"
	NAME_HASHES["NY Mets"] = "New York Mets"
	NAME_HASHES["NY Yankees"] = "New York Yankees"
	NAME_HASHES["Miami"] = "Miami Marlins"
	NAME_HASHES["Oakland"] = "Oakland Athletics"
	NAME_HASHES["Milwaukee"] = "Milwaukee Brewers"
	NAME_HASHES["Tampa Bay"] = "Tampa Bay Rays"
	NAME_HASHES["Cincinnati"] = "Cincinnati Reds"
	NAME_HASHES["Houston"] = "Houston Astros"
	NAME_HASHES["Texas"] = "Texas Rangers"
	NAME_HASHES["Minnesota"] = "Minnesota Twins"
	NAME_HASHES["Colorado"] = "Colorado Rockies"
	NAME_HASHES["Atlanta"] = "Atlanta Braves"
	NAME_HASHES["Arizona"] = "Arizona Diamondbacks"
	NAME_HASHES["Philadelphia"] = "Philadelphia Phillies"

end

app/controllers/standings_controller.rb
class StandingsController < ApplicationController
  before_action :set_standing, only: [:show, :edit, :update, :destroy]

  def scrape

  end

  # GET /standings
  # GET /standings.json
  def index
    @standings = Standing.all
  end

  # GET /standings/1
  # GET /standings/1.json
  def show
  end

  # GET /standings/new
  def new
    @standing = Standing.new
  end

  # GET /standings/1/edit
  def edit
  end

  # POST /standings
  # POST /standings.json
  def create
    @standing = Standing.new(standing_params)

    respond_to do |format|
      if @standing.save
        format.html { redirect_to @standing, notice: 'Standing was successfully created.' }
        format.json { render :show, status: :created, location: @standing }
      else
        format.html { render :new }
        format.json { render json: @standing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /standings/1
  # PATCH/PUT /standings/1.json
  def update
    respond_to do |format|
      if @standing.update(standing_params)
        format.html { redirect_to @standing, notice: 'Standing was successfully updated.' }
        format.json { render :show, status: :ok, location: @standing }
      else
        format.html { render :edit }
        format.json { render json: @standing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /standings/1
  # DELETE /standings/1.json
  def destroy
    @standing.destroy
    respond_to do |format|
      format.html { redirect_to standings_url, notice: 'Standing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_standing
      @standing = Standing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def standing_params
      params.require(:standing).permit(:team, :week, :year, :wins, :losses, :percentage)
    end
end

app/helpers/standings_helper.rb
module StandingsHelper
end

app/views/standings/_form.html.erb
<%= form_for(@standing) do |f| %>
  <% if @standing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@standing.errors.count, "error") %> prohibited this standing from being saved:</h2>

      <ul>
      <% @standing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :team %><br>
    <%= f.text_field :team %>
  </div>
  <div class="field">
    <%= f.label :week %><br>
    <%= f.number_field :week %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :wins %><br>
    <%= f.number_field :wins %>
  </div>
  <div class="field">
    <%= f.label :losses %><br>
    <%= f.number_field :losses %>
  </div>
  <div class="field">
    <%= f.label :percentage %><br>
    <%= f.text_field :percentage %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/standings/edit.html.erb
<h1>Editing standing</h1>

<%= render 'form' %>

<%= link_to 'Show', @standing %> |
<%= link_to 'Back', standings_path %>

app/views/standings/index.html.erb
<h1>Listing standings</h1>

<table>
  <thead>
    <tr>
      <th>Team</th>
      <th>Week</th>
      <th>Year</th>
      <th>Wins</th>
      <th>Losses</th>
      <th>Percentage</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @standings.each do |standing| %>
      <tr>
        <td><%= standing.team %></td>
        <td><%= standing.week %></td>
        <td><%= standing.year %></td>
        <td><%= standing.wins %></td>
        <td><%= standing.losses %></td>
        <td><%= standing.percentage %></td>
        <td><%= link_to 'Show', standing %></td>
        <td><%= link_to 'Edit', edit_standing_path(standing) %></td>
        <td><%= link_to 'Destroy', standing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Standing', new_standing_path %>

app/views/standings/new.html.erb
<h1>New standing</h1>

<%= render 'form' %>

<%= link_to 'Back', standings_path %>

app/views/standings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Team:</strong>
  <%= @standing.team %>
</p>

<p>
  <strong>Week:</strong>
  <%= @standing.week %>
</p>

<p>
  <strong>Year:</strong>
  <%= @standing.year %>
</p>

<p>
  <strong>Wins:</strong>
  <%= @standing.wins %>
</p>

<p>
  <strong>Losses:</strong>
  <%= @standing.losses %>
</p>

<p>
  <strong>Percentage:</strong>
  <%= @standing.percentage %>
</p>

<%= link_to 'Edit', edit_standing_path(@standing) %> |
<%= link_to 'Back', standings_path %>