config/routes.rb
Rails.application.routes.draw do
  resources :standings

  resources :keyvals

  resources :scrape_configs do 
    member do
      get :clone
    end
  end

  resources :images

  resources :widgets

  resources :publish_checkers

  resources :ranks

  root 'ranks#index'

  get 'ranks' => 'ranks#index'

  get 'ranks/week/:week/' => 'ranks#indexWeek'

  get 'statistics' => 'statistics#index'
  get 'about' => 'statistics#about'

end

app/models/scrape_config.rb
class ScrapeConfig < ActiveRecord::Base
end

app/controllers/scrape_configs_controller.rb
class ScrapeConfigsController < ApplicationController

  http_basic_authenticate_with name: "tcrosley", password: "tmoney"

  before_action :set_scrape_config, only: [:show, :edit, :update, :destroy]

  # GET /scrape_configs
  # GET /scrape_configs.json
  def index
    @scrape_configs = ScrapeConfig.all.order(year: :desc, week: :desc)
  end

  # GET /scrape_configs/1
  # GET /scrape_configs/1.json
  def show
  end

  # GET /scrape_configs/new
  def new
    @scrape_config = ScrapeConfig.new
  end

  def clone
    old_record = ScrapeConfig.find(params[:id])
    @new_record = ScrapeConfig.create(:website => old_record.website, :url => old_record.url, :rank_xpath => old_record.rank_xpath,
      :rank_regex => old_record.rank_regex, :team_xpath => old_record.team_xpath, :team_regex => old_record.team_regex,
      :description_xpath => old_record.description_xpath, :description_regex => old_record.description_regex, 
      :update_checker_xpath => old_record.update_checker_xpath, :update_checker_regex => old_record.update_checker_regex,
      :week => old_record.week + 1, :year => old_record.year)
    redirect_to edit_scrape_config_path(@new_record.id)
  end

  # GET /scrape_configs/1/edit
  def edit
  end

  # POST /scrape_configs
  # POST /scrape_configs.json
  def create
    @scrape_config = ScrapeConfig.new(scrape_config_params)

    respond_to do |format|
      if @scrape_config.save
        format.html { redirect_to @scrape_config, notice: 'Scrape config was successfully created.' }
        format.json { render :show, status: :created, location: @scrape_config }
      else
        format.html { render :new }
        format.json { render json: @scrape_config.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scrape_configs/1
  # PATCH/PUT /scrape_configs/1.json
  def update
    respond_to do |format|
      if @scrape_config.update(scrape_config_params)
        format.html { redirect_to @scrape_config, notice: 'Scrape config was successfully updated.' }
        format.json { render :show, status: :ok, location: @scrape_config }
      else
        format.html { render :edit }
        format.json { render json: @scrape_config.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scrape_configs/1
  # DELETE /scrape_configs/1.json
  def destroy
    @scrape_config.destroy
    respond_to do |format|
      format.html { redirect_to scrape_configs_url, notice: 'Scrape config was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scrape_config
      @scrape_config = ScrapeConfig.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scrape_config_params
      params.require(:scrape_config).permit(:website, :url, :rank_xpath, :rank_regex, :team_xpath, :team_regex, :description_xpath, :description_regex, :update_checker_xpath, :update_checker_regex, :week, :year)
    end
end

app/helpers/scrape_configs_helper.rb
module ScrapeConfigsHelper
end

app/views/scrape_configs/_form.html.erb
<%= form_for(@scrape_config) do |f| %>
  <% if @scrape_config.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scrape_config.errors.count, "error") %> prohibited this scrape_config from being saved:</h2>

      <ul>
      <% @scrape_config.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :rank_xpath %><br>
    <%= f.text_field :rank_xpath %>
  </div>
  <div class="field">
    <%= f.label :rank_regex %><br>
    <%= f.text_field :rank_regex %>
  </div>
  <div class="field">
    <%= f.label :team_xpath %><br>
    <%= f.text_field :team_xpath %>
  </div>
  <div class="field">
    <%= f.label :team_regex %><br>
    <%= f.text_field :team_regex %>
  </div>
  <div class="field">
    <%= f.label :description_xpath %><br>
    <%= f.text_field :description_xpath %>
  </div>
  <div class="field">
    <%= f.label :description_regex %><br>
    <%= f.text_field :description_regex %>
  </div>
  <div class="field">
    <%= f.label :update_checker_xpath %><br>
    <%= f.text_field :update_checker_xpath %>
  </div>
  <div class="field">
    <%= f.label :update_checker_regex %><br>
    <%= f.text_field :update_checker_regex %>
  </div>
  <div class="field">
    <%= f.label :week %><br>
    <%= f.number_field :week %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scrape_configs/edit.html.erb
<h1>Editing scrape_config</h1>

<%= render 'form' %>

<%= link_to 'Show', @scrape_config %> |
<%= link_to 'Back', scrape_configs_path %>

app/views/scrape_configs/index.html.erb
<h1>Listing scrape_configs</h1>

<table>
  <thead>
    <tr>
      <th>Website</th>
      <th>Url</th>
      <th>Rank xpath</th>
      <th>Rank regex</th>
      <th>Team xpath</th>
      <th>Team regex</th>
      <th>Description xpath</th>
      <th>Description regex</th>
      <th>Update checker xpath</th>
      <th>Update checker regex</th>
      <th>Week</th>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scrape_configs.each do |scrape_config| %>
      <tr>
        <td><%= scrape_config.website %></td>
        <td><%= scrape_config.url %></td>
        <td><%= scrape_config.rank_xpath %></td>
        <td><%= scrape_config.rank_regex %></td>
        <td><%= scrape_config.team_xpath %></td>
        <td><%= scrape_config.team_regex %></td>
        <td><%= scrape_config.description_xpath %></td>
        <td><%= scrape_config.description_regex %></td>
        <td><%= scrape_config.update_checker_xpath %></td>
        <td><%= scrape_config.update_checker_regex %></td>
        <td><%= scrape_config.week %></td>
        <td><%= scrape_config.year %></td>
        <td><%= link_to 'Show', scrape_config %></td>
        <td><%= link_to 'Edit', edit_scrape_config_path(scrape_config) %></td>
        <td><%= link_to 'Destroy', scrape_config, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Clone', scrape_config_path(scrape_config) + "/clone" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Scrape config', new_scrape_config_path %>

app/views/scrape_configs/new.html.erb
<h1>New scrape_config</h1>

<%= render 'form' %>

<%= link_to 'Back', scrape_configs_path %>

app/views/scrape_configs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Website:</strong>
  <%= @scrape_config.website %>
</p>

<p>
  <strong>Url:</strong>
  <%= @scrape_config.url %>
</p>

<p>
  <strong>Rank xpath:</strong>
  <%= @scrape_config.rank_xpath %>
</p>

<p>
  <strong>Rank regex:</strong>
  <%= @scrape_config.rank_regex %>
</p>

<p>
  <strong>Team xpath:</strong>
  <%= @scrape_config.team_xpath %>
</p>

<p>
  <strong>Team regex:</strong>
  <%= @scrape_config.team_regex %>
</p>

<p>
  <strong>Description xpath:</strong>
  <%= @scrape_config.description_xpath %>
</p>

<p>
  <strong>Description regex:</strong>
  <%= @scrape_config.description_regex %>
</p>

<p>
  <strong>Update checker xpath:</strong>
  <%= @scrape_config.update_checker_xpath %>
</p>

<p>
  <strong>Update checker regex:</strong>
  <%= @scrape_config.update_checker_regex %>
</p>

<p>
  <strong>Week:</strong>
  <%= @scrape_config.week %>
</p>

<p>
  <strong>Year:</strong>
  <%= @scrape_config.year %>
</p>

<%= link_to 'Edit', edit_scrape_config_path(@scrape_config) %> |
<%= link_to 'Back', scrape_configs_path %>