config/routes.rb
Rails.application.routes.draw do
  resources :standings

  resources :keyvals

  resources :scrape_configs do 
    member do
      get :clone
    end
  end

  resources :images

  resources :widgets

  resources :publish_checkers

  resources :ranks

  root 'ranks#index'

  get 'ranks' => 'ranks#index'

  get 'ranks/week/:week/' => 'ranks#indexWeek'

  get 'statistics' => 'statistics#index'
  get 'about' => 'statistics#about'

end

app/models/publish_checker.rb
class PublishChecker < ActiveRecord::Base
end

app/controllers/publish_checkers_controller.rb
class PublishCheckersController < ApplicationController

  http_basic_authenticate_with name: "tcrosley", password: "tmoney"

  before_action :set_publish_checker, only: [:show, :edit, :update, :destroy]

  # GET /publish_checkers
  # GET /publish_checkers.json
  def index
    @publish_checkers = PublishChecker.all.order(year: :desc, week: :desc)
  end

  # GET /publish_checkers/1
  # GET /publish_checkers/1.json
  def show
  end

  # GET /publish_checkers/new
  def new
    @publish_checker = PublishChecker.new
  end

  # GET /publish_checkers/1/edit
  def edit
  end

  # POST /publish_checkers
  # POST /publish_checkers.json
  def create
    @publish_checker = PublishChecker.new(publish_checker_params)

    respond_to do |format|
      if @publish_checker.save
        format.html { redirect_to @publish_checker, notice: 'Publish checker was successfully created.' }
        format.json { render :show, status: :created, location: @publish_checker }
      else
        format.html { render :new }
        format.json { render json: @publish_checker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publish_checkers/1
  # PATCH/PUT /publish_checkers/1.json
  def update
    respond_to do |format|
      if @publish_checker.update(publish_checker_params)
        format.html { redirect_to @publish_checker, notice: 'Publish checker was successfully updated.' }
        format.json { render :show, status: :ok, location: @publish_checker }
      else
        format.html { render :edit }
        format.json { render json: @publish_checker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publish_checkers/1
  # DELETE /publish_checkers/1.json
  def destroy
    @publish_checker.destroy
    respond_to do |format|
      format.html { redirect_to publish_checkers_url, notice: 'Publish checker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publish_checker
      @publish_checker = PublishChecker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publish_checker_params
      params.require(:publish_checker).permit(:website, :publish_tok, :week, :year)
    end
end

app/helpers/publish_checkers_helper.rb
module PublishCheckersHelper
end

app/views/publish_checkers/_form.html.erb
<%= form_for(@publish_checker) do |f| %>
  <% if @publish_checker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@publish_checker.errors.count, "error") %> prohibited this publish_checker from being saved:</h2>

      <ul>
      <% @publish_checker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :publish_tok %><br>
    <%= f.text_field :publish_tok %>
  </div>
  <div class="field">
    <%= f.label :week %><br>
    <%= f.number_field :week %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/publish_checkers/edit.html.erb
<h1>Editing publish_checker</h1>

<%= render 'form' %>

<%= link_to 'Show', @publish_checker %> |
<%= link_to 'Back', publish_checkers_path %>

app/views/publish_checkers/index.html.erb
<h1>Listing publish_checkers</h1>

<table>
  <thead>
    <tr>
      <th>Website</th>
      <th>Publish tok</th>
      <th>Week</th>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @publish_checkers.each do |publish_checker| %>
      <tr>
        <td><%= publish_checker.website %></td>
        <td><%= publish_checker.publish_tok %></td>
        <td><%= publish_checker.week %></td>
        <td><%= publish_checker.year %></td>
        <td><%= link_to 'Show', publish_checker %></td>
        <td><%= link_to 'Edit', edit_publish_checker_path(publish_checker) %></td>
        <td><%= link_to 'Destroy', publish_checker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Publish checker', new_publish_checker_path %>

app/views/publish_checkers/new.html.erb
<h1>New publish_checker</h1>

<%= render 'form' %>

<%= link_to 'Back', publish_checkers_path %>

app/views/publish_checkers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Website:</strong>
  <%= @publish_checker.website %>
</p>

<p>
  <strong>Publish tok:</strong>
  <%= @publish_checker.publish_tok %>
</p>

<p>
  <strong>Week:</strong>
  <%= @publish_checker.week %>
</p>

<p>
  <strong>Year:</strong>
  <%= @publish_checker.year %>
</p>

<%= link_to 'Edit', edit_publish_checker_path(@publish_checker) %> |
<%= link_to 'Back', publish_checkers_path %>